theme: jekyll-theme-minimal
title: [Rubyx D6 Warehouse Developer Portal]
description: [Here are listed the documentation needed to perform SQL queries on Rubyx D6 warehouse using Google BigQuery API]
logo: assets/img/RubyxLogoHori.png
