theme: jekyll-theme-minimal
title: [D6 Data Warehouse BigQuery API]
description: [Here are listed the documentation needed to perform SQL queries on Rubyx D6 data warehouse using the Google BigQuery API.]
