theme: jekyll-theme-minimal
title: [Rubyx D6 Warehouse BigQuery API Doc]
description: [Here are listed the documentation needed to perform SQL queries on Rubyx D6 data warehouse using the Google BigQuery API.]
logo: assets/img/RubyxLogoHori.png
